# Generated by Django 3.1 on 2020-09-14 21:12

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryAccessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='api.brand')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_1', to='api.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories_1',
                'db_table': 'subcategory_1',
            },
        ),
        migrations.CreateModel(
            name='SubCategory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subcat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_2', to='api.subcategory1')),
            ],
            options={
                'verbose_name_plural': 'subcategories_2',
                'db_table': 'subcategory_2',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.storage_dir)),
                ('short_desc', models.CharField(max_length=200, verbose_name='Short Description')),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('in_the_box', models.JSONField(default=api.models.json_default)),
                ('specs', models.JSONField(default=api.models.json_default)),
                ('package_dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(default='Generic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='api.brand')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('model_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='api.modelname', to_field='name')),
                ('subcat_1_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subcategory1')),
                ('subcat_2_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subcategory2')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='CategoryAccessoryJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_field', models.IntegerField(blank=True, unique=True)),
                ('accessory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_join', to='api.categoryaccessories', to_field='cat_id')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_join', to='api.category')),
            ],
        ),
    ]
