# Generated by Django 3.1 on 2020-08-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='api.category', to_field='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_cat_id_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='api.subcategory1', to_field='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_cat_id_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='api.subcategory2', to_field='name'),
        ),
    ]
