# Generated by Django 3.1 on 2020-08-23 05:43

import api.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_image', models.ImageField(upload_to=api.model_utils.storage_dir)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('prod_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
