# Generated by Django 3.1 on 2020-08-10 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200810_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='features_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.audiointerfacefeatures'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiointerfacefeatures',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_interface_features', to='api.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(default='Generic', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.brand'),
        ),
        migrations.AlterField(
            model_name='products',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
        ),
    ]
