# Generated by Django 3.1 on 2020-09-14 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200914_2337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryAccessories',
            new_name='CategoryDouble',
        ),
        migrations.CreateModel(
            name='CategoryBoughtTogetherJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_field', models.IntegerField(blank=True, unique=True)),
                ('bought_together_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_join', to='api.categorydouble', to_field='cat_id')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_together_join', to='api.category')),
            ],
            options={
                'verbose_name_plural': 'category_bought_together',
                'db_table': 'category_bought_together',
            },
        ),
    ]
