# Generated by Django 3.1 on 2020-08-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200825_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_cat_id_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_cat_id_2',
        ),
        migrations.AddField(
            model_name='accessories',
            name='cat_name',
            field=models.CharField(choices=[('NONE', 'None')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessories',
            name='sub_cat_1_name',
            field=models.CharField(choices=[('NONE', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accessories',
            name='sub_cat_2_name',
            field=models.CharField(choices=[('NONE', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boughttogether',
            name='cat_name',
            field=models.CharField(choices=[('NONE', 'None')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boughttogether',
            name='sub_cat_1_name',
            field=models.CharField(choices=[('NONE', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boughttogether',
            name='sub_cat_2_name',
            field=models.CharField(choices=[('NONE', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cat_name',
            field=models.CharField(choices=[('NONE', 'None')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sub_cat_1_name',
            field=models.CharField(choices=[('NONE', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_cat_2_name',
            field=models.CharField(choices=[('NONE', 'None')], default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('NONE', 'None')], max_length=100),
        ),
    ]
