# Generated by Django 3.1 on 2020-08-10 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200810_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='features_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.audiointerfacefeatures'),
        ),
    ]
