# Generated by Django 3.1 on 2020-09-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subcat1accessoryjoin_subcat1boughttogetherjoin_subcat1double'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcat1accessoryjoin',
            name='accessory_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_join', to='api.subcat1double', to_field='subcat_1_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcat1accessoryjoin',
            name='subcat_1_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accessory_join', to='api.subcategory1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcat1boughttogetherjoin',
            name='accessory_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bought_join', to='api.subcat1double', to_field='subcat_1_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcat1boughttogetherjoin',
            name='subcat_1_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bought_together_join', to='api.subcategory1'),
            preserve_default=False,
        ),
    ]
