# Generated by Django 3.1 on 2020-09-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='full_image',
            new_name='file_path',
        ),
        migrations.AlterField(
            model_name='modelname',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='api.brand'),
        ),
    ]
