# Generated by Django 3.1 on 2020-09-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200902_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfeatures',
            name='subcat_1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subcategory1'),
        ),
        migrations.AddField(
            model_name='mainfeatures',
            name='subcat_2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subcategory2'),
        ),
        migrations.AlterField(
            model_name='mainfeatures',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
    ]
