# Generated by Django 3.1 on 2020-09-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200921_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcat1boughttogetherjoin',
            old_name='accessory_id',
            new_name='bought_together_id',
        ),
        migrations.RenameField(
            model_name='subcat2boughttogetherjoin',
            old_name='accessory_id',
            new_name='bought_together_id',
        ),
    ]
