# Generated by Django 3.1 on 2020-09-22 01:13

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200921_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory2',
            old_name='subcat_id',
            new_name='subcat_2_id',
        ),
        migrations.CreateModel(
            name='SubCategory2MainFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(default=api.models.json_default)),
                ('subcat_2_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_features', to='api.subcategory2')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory1MainFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(default=api.models.json_default)),
                ('subcat_1_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_features', to='api.subcategory1')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMainFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(default=api.models.json_default)),
                ('cat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_features', to='api.category')),
            ],
        ),
    ]
