# Generated by Django 3.1 on 2020-09-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200905_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='accessories',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='api.accessories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bought_together',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='api.boughttogether'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='api.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_dimensions',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
