# Generated by Django 3.1 on 2020-09-05 08:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200905_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.storage_dir),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
