# Generated by Django 3.1 on 2020-09-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200922_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory2',
            old_name='subcat_2_id',
            new_name='subcat_1_id',
        ),
    ]
