# Generated by Django 3.1 on 2020-09-09 02:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200905_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_the_box',
            field=models.JSONField(blank=True, default=api.models.json_default),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=api.models.json_default),
        ),
    ]
