# Generated by Django 3.1 on 2020-09-09 03:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200909_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_the_box',
            field=models.JSONField(default=api.models.json_default),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(default=api.models.json_default),
        ),
    ]
