# Generated by Django 3.1 on 2020-12-09 06:32

from django.db import migrations, models
import django.db.models.deletion
import products



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alias', models.JSONField(default=products.models.json_default)),
                ('main_features', models.JSONField(default=products.models.json_default)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='products.brand')),
            ],
            options={
                'db_table': 'model_name',
            },
        ),
        migrations.CreateModel(
            name='SubCategory1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alias', models.JSONField(default=products.models.json_default)),
                ('main_features', models.JSONField(default=products.models.json_default)),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_1', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories_1',
                'db_table': 'subcategory_1',
            },
        ),
        migrations.CreateModel(
            name='SubCategory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alias', models.JSONField(default=products.models.json_default)),
                ('main_features', models.JSONField(default=products.models.json_default)),
                ('subcat_1_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_2', to='products.subcategory1')),
            ],
            options={
                'verbose_name_plural': 'subcategories_2',
                'db_table': 'subcategory_2',
            },
        ),
        migrations.CreateModel(
            name='Subcat2BoughtTogetherJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_field', models.IntegerField(blank=True, unique=True)),
                ('bought_together_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_join', to='products.subcategory2')),
                ('subcat_2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_together_join', to='products.subcategory2')),
            ],
            options={
                'verbose_name_plural': 'subcategory_2_bought_together',
                'db_table': 'subcategory_2_bought_together',
            },
        ),
        migrations.CreateModel(
            name='Subcat2AccessoryJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_field', models.IntegerField(blank=True, unique=True)),
                ('accessory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_join', to='products.subcategory2')),
                ('subcat_2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_join', to='products.subcategory2')),
            ],
            options={
                'verbose_name_plural': 'subcategory_2_accessories',
                'db_table': 'subcategory_2_accessories',
            },
        ),
        migrations.CreateModel(
            name='Subcat1BoughtTogetherJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_field', models.IntegerField(blank=True, unique=True)),
                ('bought_together_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_join', to='products.subcategory1')),
                ('subcat_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_together_join', to='products.subcategory1')),
            ],
            options={
                'verbose_name_plural': 'subcategory_1_bought_together',
                'db_table': 'subcategory_1_bought_together',
            },
        ),
        migrations.CreateModel(
            name='Subcat1AccessoryJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_field', models.IntegerField(blank=True, unique=True)),
                ('accessory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_join', to='products.subcategory1')),
                ('subcat_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_join', to='products.subcategory1')),
            ],
            options={
                'verbose_name_plural': 'subcategory_1_accessories',
                'db_table': 'subcategory_1_accessories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comes_in_pairs', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.storage_dir)),
                ('short_desc', models.CharField(max_length=200, verbose_name='Short Description')),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('in_the_box', models.JSONField(default=products.models.json_default)),
                ('specs', models.JSONField(default=products.models.json_default)),
                ('package_dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(default='Generic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.brand')),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('model_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.modelname', to_field='name')),
                ('subcat_1_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory1')),
                ('subcat_2_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory2')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='CategoryBoughtTogetherJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_field', models.IntegerField(blank=True, unique=True)),
                ('bought_together_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_join', to='products.category')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_together_join', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'category_bought_together',
                'db_table': 'category_bought_together',
            },
        ),
        migrations.CreateModel(
            name='CategoryAccessoryJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_field', models.IntegerField(blank=True, unique=True)),
                ('accessory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_join', to='products.category')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_join', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'category_accessories',
                'db_table': 'category_accessories',
            },
        ),
    ]
