# Generated by Django 3.1 on 2020-12-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs_from_bhpv',
            field=models.BooleanField(default=True),
        ),
    ]
