# Generated by Django 3.1 on 2020-12-10 07:35

from django.db import migrations
import products.models
import products.utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201210_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='alias',
            field=products.utils.model_utils.ListJSONField(default=products.models.json_default),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_features',
            field=products.utils.model_utils.ListJSONField(default=products.models.json_default),
        ),
    ]
