# Generated by Django 3.1 on 2020-12-10 09:02

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201210_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.JSONField(default=products.models.json_default),
        ),
    ]
