# Generated by Django 3.1 on 2020-12-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='test',
        ),
    ]
