# Generated by Django 3.1 on 2020-12-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201211_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='category',
            name='main_features',
        ),
    ]
