# Generated by Django 3.1 on 2020-12-11 05:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201211_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory1',
            name='new_alias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
        migrations.AddField(
            model_name='subcategory1',
            name='new_main_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
        migrations.AddField(
            model_name='subcategory2',
            name='new_alias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
        migrations.AddField(
            model_name='subcategory2',
            name='new_main_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
    ]
