# Generated by Django 3.1 on 2020-12-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201211_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory1',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='subcategory1',
            name='main_features',
        ),
        migrations.RemoveField(
            model_name='subcategory2',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='subcategory2',
            name='main_features',
        ),
    ]
