# Generated by Django 3.1 on 2020-12-11 22:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201211_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None),
        ),
    ]
