# Generated by Django 3.1 on 2020-12-11 22:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201211_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
