# Generated by Django 3.1 on 2020-12-12 02:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201211_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features_alias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None),
        ),
    ]
