# Generated by Django 3.1 on 2020-12-14 14:09

from django.db import migrations, models
import products.utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_features_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[products.utils.model_utils.CrossModelUniqueNameValidator]),
        ),
    ]
