# Generated by Django 3.1 on 2020-12-16 06:45

from django.db import migrations, models
import products.models
import products.utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201214_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('model_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'unique_category',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[products.utils.model_utils.CrossModelUniqueNameValidator(products.models.UniqueCategory)]),
        ),
        migrations.AlterField(
            model_name='subcategory1',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[products.utils.model_utils.CrossModelUniqueNameValidator(products.models.UniqueCategory)]),
        ),
        migrations.AlterField(
            model_name='subcategory2',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[products.utils.model_utils.CrossModelUniqueNameValidator(products.models.UniqueCategory)]),
        ),
    ]
