# Generated by Django 3.1 on 2020-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201216_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquecategory',
            name='cat_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
