# Generated by Django 3.1 on 2020-12-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_uniquecategory_cat_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='uniquecategory',
            constraint=models.UniqueConstraint(fields=('model_name', 'cat_id'), name='whatever'),
        ),
    ]
