# Generated by Django 3.1 on 2020-12-16 15:35

from django.db import migrations, models
import products.models
import products.utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20201216_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[products.utils.model_utils.CrossModelUniqueNameValidator(products.models.UniqueCategory)]),
        ),
        migrations.AlterField(
            model_name='subcategory1',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[products.utils.model_utils.CrossModelUniqueNameValidator(products.models.UniqueCategory)]),
        ),
        migrations.AlterField(
            model_name='subcategory2',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[products.utils.model_utils.CrossModelUniqueNameValidator(products.models.UniqueCategory)]),
        ),
    ]
