# Generated by Django 3.1 on 2021-01-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210110_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryaccessoryjoin',
            name='hash_field',
        ),
        migrations.RemoveField(
            model_name='categoryboughttogetherjoin',
            name='hash_field',
        ),
        migrations.RemoveField(
            model_name='subcat1accessoryjoin',
            name='hash_field',
        ),
        migrations.RemoveField(
            model_name='subcat1boughttogetherjoin',
            name='hash_field',
        ),
        migrations.RemoveField(
            model_name='subcat2accessoryjoin',
            name='hash_field',
        ),
        migrations.RemoveField(
            model_name='subcat2boughttogetherjoin',
            name='hash_field',
        ),
        migrations.AddConstraint(
            model_name='categoryaccessoryjoin',
            constraint=models.UniqueConstraint(fields=('cat_id', 'accessory_id'), name='cat_acc_join'),
        ),
        migrations.AddConstraint(
            model_name='categoryboughttogetherjoin',
            constraint=models.UniqueConstraint(fields=('cat_id', 'bought_together_id'), name='cat_b2g_join'),
        ),
    ]
