# Generated by Django 3.1 on 2021-01-12 12:03

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20210111_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=models.SET(products.models.get_generic_brand), related_name='product', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.modelname', to_field='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcat_1_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.subcategory1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcat_2_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.subcategory2'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'model_name', 'variants'), name='product_variants'),
        ),
        migrations.AddConstraint(
            model_name='subcat1accessoryjoin',
            constraint=models.UniqueConstraint(fields=('subcat_1_id', 'accessory_id'), name='subcat1_acc_join'),
        ),
        migrations.AddConstraint(
            model_name='subcat1boughttogetherjoin',
            constraint=models.UniqueConstraint(fields=('subcat_1_id', 'bought_together_id'), name='subcat1_b2g_join'),
        ),
        migrations.AddConstraint(
            model_name='subcat2accessoryjoin',
            constraint=models.UniqueConstraint(fields=('subcat_2_id', 'accessory_id'), name='subcat2_acc_join'),
        ),
        migrations.AddConstraint(
            model_name='subcat2boughttogetherjoin',
            constraint=models.UniqueConstraint(fields=('subcat_2_id', 'bought_together_id'), name='subcat2_b2g_join'),
        ),
    ]
