# Generated by Django 3.1 on 2021-01-12 12:07

from django.db import migrations, models
import django.db.models.deletion


def copy_model_references(apps, schema_editor):
    """
    Copies model_name id's to new field mo_name, field will be renamed later
    """
    prod = apps.get_model("products", "Product")
    for product in prod.objects.all():
        product.mo_name = product.model_name
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20210112_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mo_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro', to='products.modelname'),
        ),
        # Python routine to copy model_name id's
        migrations.RunPython(copy_model_references),
    ]
