# Generated by Django 3.1 on 2021-01-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_product_mo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_name',
        ),
    ]
