# Generated by Django 3.1 on 2021-01-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_product_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mo_name',
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.modelname'),
        ),
    ]
