# Generated by Django 3.1 on 2021-03-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20210121_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.URLField(null=True, unique=True),
        ),
    ]
